# ======================
# APPLICATION
# ======================
spring.application.name=notification-system
server.port=${SERVER_PORT:8080}

# ======================
# DATABASE (PostgreSQL)
# ======================
spring.datasource.url=jdbc:postgresql://${DB_HOST:db}:${DB_PORT:5432}/${DB_NAME:notifications_db}
spring.datasource.username=${DB_USER:notifications_user}
spring.datasource.password=${DB_PASSWORD:notifications_password}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=10

# ======================
# JPA / HIBERNATE
# ======================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ======================
# SQL INIT (DISABLED)
# ======================
spring.sql.init.mode=never

# ======================
# FLYWAY (MIGRATIONS)
# ======================
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
logging.level.org.flywaydb=DEBUG

# ======================
# FAILURE SIMULATION
# ======================
notification.failure.email-rate=0.20
notification.failure.sms-rate=0.30
notification.failure.push-rate=0.10

# ======================
# RETRY CONFIG
# ======================
notification.retry.max-attempts=3

# ======================
# ACTUATOR
# ======================
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
